replicaCount: 1
image:
  repository: registry.choerodon.com.cn/hzero-hzero/jipaas-orchestration-manager
  pullPolicy: Always
preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 1200
  preInitDB:
    enable: false # 如果需要开启liquibase初始化，这里改成true
    datasource:
      url: jdbc:mysql://db.hzero.org:3306/hzero_orchestration?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hzero
      password: hzero
env:
  open:
    # Eureka 注册中心地址
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    # 服务以IP地址注册
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    # 是否启用配置中心
    SPRING_CLOUD_CONFIG_ENABLED: false
    # 配置中心地址
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    # 数据库地址
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.org:3306/hzero_orchestration?useUnicode=true&characterEncoding=utf-8&useSSL=false
    # 数据库用户名
    SPRING_DATASOURCE_USERNAME: hzero
    # 数据库密码
    SPRING_DATASOURCE_PASSWORD: hzero
    # 连接池最小空闲连接数
    SPRING_DATASOURCE_MINIMUM_IDLE: 20
    # 连接池允许的最大连接数
    SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 200
    # 等待连接池分配连接的最大时长（毫秒）
    SPRING_DATASOURCE_CONNECTION_TIMEOUT: 30000
    # Redis host
    SPRING_REDIS_HOST: redis.hzero.org
    # Redis port
    SPRING_REDIS_PORT: 6379
    # Redis DB
    SPRING_REDIS_DATABASE: 1
    # 资源池中最大连接数
    # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
    SPRING_REDIS_POOL_MAX_ACTIVE: 50
    # 资源池运行最大空闲的连接数
    # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
    SPRING_REDIS_POOL_MAX_IDLE: 50
    # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
    # 默认 -1 表示永不超时，设置5秒
    SPRING_REDIS_POOL_MAX_WAIT: 5000
    # Hystrix 熔断超时时间
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 40000
    # 执行命令线程池的核心线程数，也是命令执行的最大并发量
    HYSTRIX_THREADPOOL_DEFAULT_CORE_SIZE: 100
    # 最大执行线程数
    HYSTRIX_THREADPOOL_DEFAULT_MAXIMUM_SIZE: 200
    # BlockingQueue的最大队列数，默认值-1
    HYSTRIX_THREADPOOL_DEFAULT_MAX_QUEUE_SIZE: 1000
    # 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5, 需与maxQueueSize同时使用
    HYSTRIX_THREADPOOL_DEFAULT_QUEUE_SIZE_REJECTION_THRESHOLD: 1000
    # Ribbon 读取超时时间
    RIBBON_READ_TIMEOUT: 30000
    # Ribbon 连接超时时间
    RIBBON_CONNECT_TIMEOUT: 3000
    # IO线程数, 它主要执行非阻塞的任务
    SERVER_UNDERTOW_IO_THREADS: 4
    # 阻塞任务线程池
    SERVER_UNDERTOW_WORKER_THREADS: 128
    # 每块buffer的空间大小，越小空间被利用越充分
    SERVER_UNDERTOW_BUFFER_SIZE: 1024
    # none（默认）、basic（记录请求方法，URL，响应状态代码以及执行时间（适合生产环境））
    FEIGN_CLIENT_DEFAULT_LOGGER_LEVEL: basic
    # 分布式锁Redis地址
    HZERO_LOCK_REDIS_HOST: ${spring.redis.host}
    # 分布式锁Redis端口
    HZERO_LOCK_REDIS_PORT: ${spring.redis.port}
    # 分布式锁Redis数据库
    HZERO_LOCK_REDIS_DATABASE: ${spring.redis.database}
    # 是否开启Netty Epoll功能
    HZERO_ORCHESTRATION_NETTY_EPOLL_ENABLED: false
    # Worker的IP地址，单机模式下生效
    HZERO_ORCHESTRATION_WORKER_IP: 0.0.0.0
    # 数据库所有者模式，例如 SqlServer 下的 dbo/guest
    HZERO_DB_OWNER: null
    # 日志级别
    LOG_LEVEL: info
    JAVA_OPTS: |
      -Xms1024m -Xmx1536m
metrics:
  path: /actuator/prometheus
  group: spring-boot
logs:
  parser: spring-boot
persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # subPath:
service:
  enabled: false
  type: ClusterIP
  port: 8195
  name: jipaas-orchestration-manager
deployment:
  managementPort: 8196
ingress:
  enabled: false
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.7Gi
  requests:
    # cpu: 100m
    memory: 1.2Gi
